services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    startCommand: echo "Starting via Dockerfile"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: ':memory:'